baseURL = 'https://cadence.nightnoryu.com/'
locale = 'en-us'
title = 'Cadence - Manage your gigs'
theme = 'PaperMod'

enableRobotsTXT = true
enableEmoji = true

# ---------------
# Navigation
# ---------------

[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 2

[[menu.main]]
  identifier = 'app'
  name = 'Open App'
  url = 'https://app.cadence.nightnoryu.com/'
  weight = 3

# ---------------
# Homepage
# ---------------

[params.profileMode]
  enabled = true
  title = 'Cadence'
  subtitle = 'Repertoire manager for gigging bands.'
  imageUrl = 'images/logo.png'
  imageWidth = 120
  imageHeight = 120

  [[params.profileMode.buttons]]
    name = 'Open App'
    url = 'https://app.cadence.nightnoryu.com/'

# ---------------
# Socials
# ---------------

[[params.socialIcons]]
  name = 'telegram'
  url = 'https://t.me/nightnoryu'

[[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/nightnoryu'

[params.label]
  text = 'Cadence'

[params.assets]
  favicon = 'favicon.png'
