baseURL = 'https://cadence.nightnoryu.com/'
locale = 'en-us'
title = 'Cadence - Manage your gigs'
theme = 'PaperMod'

enableRobotsTXT = true
enableEmoji = true

# ---------------
# Navigation
# ---------------

[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 2

[[menu.main]]
  identifier = 'app'
  name = 'Open App'
  url = 'https://app.cadence.nightnoryu.com'
  weight = 3

# ---------------
# Homepage
# ---------------

[params.profileMode]
  enabled = true
  title = 'Cadence'
  subtitle = 'Repertoire manager for gigging bands.'
  imageUrl = 'images/logo.webp'
  imageWidth = 180
  imageHeight = 180

  [[params.profileMode.buttons]]
    name = 'Open App'
    url = 'https://app.cadence.nightnoryu.com'

# ---------------
# Socials
# ---------------

[[params.socialIcons]]
  name = 'telegram'
  url = 'https://t.me/nightnoryu'

[[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/cadence-muse'

[params.label]
  text = 'Cadence'

[params.assets]
  favicon = 'favicon.ico'
  favicon16x16 = 'favicon-16x16.png'
  favicon32x32 = 'favicon-32x32.png'
  apple_touch_icon = 'apple-touch-icon.png'
